spring:
  application:
    name: EmployeeManagement
  datasource:
    url: jdbc:mysql://localhost:3307/ems_prod
    username: root
    password: 123456
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
server:
  error:
    include-stacktrace: never
  port: 8082