spring:
  application:
    name: EmployeeManagement
  datasource:
    url: jdbc:h2:mem:ems_prod;DB_CLOSE_DELAY=-1
    username: root
    password: 123456
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    database: mysql
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
server:
  error:
    include-stacktrace: never
  port: 8082


